// CountPrimesInRange.java

import java.util.Arrays; // Import the Arrays class to use its utility methods like fill().

/**
 * This class addresses the query-based problem of counting prime numbers
 * within a given range [L, R]. It provides two solutions:
 * 1. A brute-force method that re-calculates for each query.
 * 2. An optimal method that pre-computes primes using a Sieve and then
 * answers each query in constant time using a prefix sum array.
 */
public class CountPrimesInRange {

    // ==================================================================================
    // Optimal Method Variables (Pre-computation)
    // ==================================================================================
    
    // Define the maximum possible value for R in any query.
    // All pre-computation will be done up to this limit.
    private static final int MAX_N = 100000;

    // A boolean array to store prime information, generated by the Sieve.
    // isPrimeSieve[i] will be true if 'i' is prime, false otherwise.
    private static boolean[] isPrimeSieve = new boolean[MAX_N + 1];

    // An integer array to store the count of primes up to index 'i'.
    // This is also known as a prefix sum or prefix count array.
    private static int[] prefixPrimeCount = new int[MAX_N + 1];

    // A static initializer block. This code runs exactly once when the class is
    // loaded into memory, making it the perfect place for our one-time pre-computation.
    static {
        precomputePrimes(); // Call the pre-computation method.
    }


    /**
     * The main method to drive the program. It demonstrates both the brute-force
     * and optimal methods by running a series of sample queries.
     * @param args Command line arguments (not used).
     */
    public static void main(String[] args) {
        // Define a list of sample queries, where each query is a range [L, R].
        int[][] queries = {{1, 10}, {10, 50}, {25, 100}, {500, 1000}};

        System.out.println("--- Method 1: Brute-Force per Query ---");
        // Loop through each query to test the brute-force method.
        for (int[] query : queries) {
            int L = query[0]; // Get the left bound of the range.
            int R = query[1]; // Get the right bound of the range.
            int count = bruteForceQuery(L, R); // Calculate the count of primes.
            // Print the result for the current query.
            System.out.println("Count of primes in [" + L + ", " + R + "] is: " + count);
        }

        System.out.println("\n--- Method 2: Optimal using Pre-computation ---");
        // Loop through each query to test the optimal method.
        for (int[] query : queries) {
            int L = query[0]; // Get the left bound of the range.
            int R = query[1]; // Get the right bound of the range.
            int count = optimalQuery(L, R); // Get the count of primes instantly.
            // Print the result for the current query.
            System.out.println("Count of primes in [" + L + ", " + R + "] is: " + count);
        }
    }


    // ==================================================================================
    // Method 1: Brute-Force Approach
    // ==================================================================================
    /*
     * Time Complexity: O(Q * (R-L) * sqrt(R)) for Q queries.
     * Space Complexity: O(1)
     *
     * Explanation: For each of the 'Q' queries, we loop from L to R (a range of size R-L).
     * Inside the loop, we call the `isPrime` helper, which itself can take up to O(sqrt(R)) time.
     * This is highly inefficient as we re-calculate primality for the same numbers again and
     * again across different, potentially overlapping, queries.
     *
     * Visualization:
     * Query 1: [10, 30] -> Check 10, 11, 12, ... 30 for primality one by one.
     * Query 2: [20, 40] -> Check 20, 21, 22, ... 40 for primality one by one.
     * The primality of numbers from 20 to 30 is wastefully computed twice.
     */
    public static int bruteForceQuery(int L, int R) {
        int count = 0; // Initialize a counter for prime numbers to zero.
        for (int i = L; i <= R; i++) { // Loop through every number in the range [L, R].
            if (isPrime(i)) { // Check if the current number 'i' is prime.
                count++; // If it is, increment the counter.
            }
        }
        return count; // Return the total count of primes found.
    }

    /**
     * Helper function for the brute-force method to check if a single number is prime.
     * @param num The number to check.
     * @return true if the number is prime, false otherwise.
     */
    private static boolean isPrime(int num) {
        if (num <= 1) return false; // 1 and numbers less than 1 are not prime.
        for (int i = 2; i * i <= num; i++) { // Loop from 2 up to the square root of the number.
            if (num % i == 0) return false; // If a divisor is found, it's not prime.
        }
        return true; // If no divisors are found, the number is prime.
    }


    // ==================================================================================
    // Method 2: Optimal Approach (Pre-computation + O(1) Query)
    // ==================================================================================
    /*
     * Pre-computation Time: O(MAX_N * log(log(MAX_N)))
     * Query Time: O(1)
     * Total Time for Q queries: O(MAX_N * log(log(MAX_N)) + Q)
     * Space Complexity: O(MAX_N)
     *
     * Explanation:
     * This approach invests time upfront to calculate all primes up to a maximum limit (MAX_N).
     * 1. Sieve: We first use a Sieve of Eratosthenes to find all primes up to MAX_N.
     * 2. Prefix Sum: We then build a `prefixPrimeCount` array where `prefixPrimeCount[i]` stores
     * the total number of primes from 0 to 'i'.
     * 3. Query: With this pre-computed array, the number of primes in any range [L, R] can
     * be found in a single subtraction: `prefixPrimeCount[R] - prefixPrimeCount[L-1]`.
     *
     * Visualization:
     * 1. Sieve marks primes up to 10: isPrimeSieve -> [F, F, T, T, F, T, F, T, F, F, F]
     * 2. Prefix Sum array is built:
     * prefixPrimeCount[0] = 0
     * prefixPrimeCount[1] = 0
     * prefixPrimeCount[2] = 1 (prime 2)
     * prefixPrimeCount[3] = 2 (primes 2, 3)
     * prefixPrimeCount[4] = 2
     * prefixPrimeCount[5] = 3 (primes 2, 3, 5)
     * ...and so on.
     * 3. Query for [3, 7]:
     * Result = prefixPrimeCount[7] - prefixPrimeCount[3-1]
     * = prefixPrimeCount[7] - prefixPrimeCount[2]
     * = 4 - 1 = 3. (The primes are 3, 5, 7).
     */
    private static void precomputePrimes() {
        // Step 1: Sieve of Eratosthenes
        Arrays.fill(isPrimeSieve, true); // Assume all numbers are prime initially.
        isPrimeSieve[0] = isPrimeSieve[1] = false; // 0 and 1 are not prime.
        for (int p = 2; p * p <= MAX_N; p++) { // Loop from 2 to sqrt(MAX_N).
            if (isPrimeSieve[p]) { // If 'p' is a prime number...
                for (int i = p * p; i <= MAX_N; i += p) { // ...mark all of its multiples as not prime.
                    isPrimeSieve[i] = false;
                }
            }
        }

        // Step 2: Build the Prefix Sum Array
        prefixPrimeCount[0] = 0; // There are no primes up to 0.
        for (int i = 1; i <= MAX_N; i++) { // Loop from 1 to MAX_N.
            prefixPrimeCount[i] = prefixPrimeCount[i - 1]; // Carry over the count from the previous number.
            if (isPrimeSieve[i]) { // If the current number 'i' is prime...
                prefixPrimeCount[i]++; // ...increment the count.
            }
        }
    }

    /**
     * Answers the query in O(1) time using the pre-computed prefix sum array.
     * @param L The left bound of the range (inclusive).
     * @param R The right bound of the range (inclusive).
     * @return The count of prime numbers in the range [L, R].
     */
    public static int optimalQuery(int L, int R) {
        // Handle the edge case where L is 0 or 1.
        if (L <= 1) {
            // The number of primes from 1 to R is simply the pre-calculated value at R.
            return prefixPrimeCount[R];
        }
        // The count of primes in [L, R] is the count up to R minus the count up to L-1.
        // This effectively isolates the count for the desired range.
        return prefixPrimeCount[R] - prefixPrimeCount[L - 1];
    }
}